remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: "World-to-Words: Grounded Open Vocabulary Acquisition through Fast Mapping in Vision-Language Models"
description: "Ziqiao Ma *, Jiayi Pan *, Joyce Chai"
